// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;
using TestAmericanFootball2.Models;

namespace TestAmericanFootball2.Migrations
{
    [DbContext(typeof(TestAmericanFootball2Context))]
    [Migration("20180808055811_Mod_Add_Column_GainYards")]
    partial class Mod_Add_Column_GainYards
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TestAmericanFootball2.Models.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CurrentPlayer");

                    b.Property<int>("CurrentQuarter");

                    b.Property<decimal>("GainYards");

                    b.Property<int>("P1Score");

                    b.Property<int>("P2Score");

                    b.Property<string>("Player1Id");

                    b.Property<string>("Player2Id");

                    b.Property<int>("RemainOffenceNum");

                    b.Property<int>("RemainSeconds");

                    b.Property<decimal>("RemainYards");

                    b.Property<string>("Result");

                    b.HasKey("Id");

                    b.ToTable("Game");
                });

            modelBuilder.Entity("TestAmericanFootball2.Models.Movie", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Genre");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Rating");

                    b.Property<DateTime>("ReleaseDate");

                    b.Property<string>("Title");

                    b.HasKey("ID");

                    b.ToTable("Movie");
                });
#pragma warning restore 612, 618
        }
    }
}
